version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"
    networks:
      keycloak:
        aliases:
          - mysql
  keycloak:
    image: keycloak-scim-sdk:latest
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      keycloak:
        aliases:
          - keycloak
networks:
  keycloak:
